# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Maya Juman
tagline:          'EEB'
url:              http://mayajuman.github.io
baseurl:          /

author:
  name:           'Maya Juman'
  url:            https://twitter.com/mayajuman

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/mayajuman/mayajuman.github.io
