# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Maya Juman
tagline:          'A Jekyll theme'
description:      'Ecology and Evolutionary Biology'
url:              http://mayajuman.github.io
baseurl:          /

author:
  name:           'Mark Otto'
  url:            https://twitter.com/

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/mayajuman/mayajuman.github.io
