# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Maya Juman
description:      'Ecology and Evolutionary Biology'
tagline:          'EEB'
url:              http://mayajuman.github.io
baseurl:          /

author:
  name:           'Maya Juman'
  url:            https://twitter.com/mayajuman

paginate:         5

github:
  repo:           https://github.com/mayajuman/mayajuman.github.io
