# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Maya Juman
tagline:          'EEB'
description:      '(she/her/hers)'
url:              http://mayajuman.github.io
baseurl:          http://mayajuman.github.io

author:
   name:          'Maya Juman'
   twitter:    https://twitter.com/mayajuman
   email:      maya.juman@aya.yale.edu
   github:     https://github.com/mayajuman

paginate:         15

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/mayajuman/mayajuman.github.io
